[package]
name = "keithley_2230_series_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
visa-api = "0.1.2"
keithley-2230-series = "0.1.4"
egui = "0.24.1"
eframe = "0.24.1"
